downloads/index.md

The download page already links to some  wxGTK 3.0.3 unofficial packages. These are the 3.1.0 equivalents.

Add links to some wxGTK 3.1.0 unofficial packages to the Downloads page

---

_posts/2018-03-06-wxwidgets-3.0.4-released.md
downloads/index.md

This is updated for 3.0.4, except as there is no google announcement post to link to yet, I linked to the repo announcement.

Add 3.0.4 release post and update download links.

---

_blog/2019-01-14-wxwidgets-and-vcpkg.md

I recently used Microsoft's vcpkg tool to improve the way an application managed its wxWidgets (and other) dependencies.
Andrew Smart, who [released the wxWidgetsTemplate NuGet package several years ago](https://www.wxwidgets.org/news/2014/03/nuget-package-with-wxwidgets-template/), suggested I investigate this method rather than attempting to update his package for current Visual Studio & wxWidgets versions.
In conversation with Vadim Zeitlin and Andrew, Vadim suggested I produce a blog post about the experience: here it is.

Add a blog post about using vcpkg to obtain, build and provide wxWidgets

---

_data/aside.yml
_data/navigation.yml
_includes/aside.html
_includes/navigation.html

Added some separation between pages content and pages layout by adding 2 yml files in _data directory for both navigation and aside, loading them into related pages using liquid.
There is no visible changes except for the aside where the 'Solutions' card was moved below due some needed complexity to add in the aside.html include and so make the separation completed in that page.

Moved navigation and partial aside content from page layout to yml data.

---

docs/faq/windows/index.md

TBH, I believe there is a lot of information in the FAQs that in time became outdated or having little relevance.
E.g., in the MSW part it would be information about DBCS, reducing executable size, best compilers, DLLs...  I did not dare to make bold changes attempting to correct this.
And while this may be just a matter of personal preference, some parts of the FAQs read like opinions and not technical writing which I would rather avoid.

Update name of install instructions file in MSW FAQ

---

.gitignore
_cron/update_download_stats.rb
downloads/downloads.js
downloads/index.md
package.json

This shows the download counts and file size in a tooltip. The download statistic is always up to date directly from github via javascript.

Show download statistics on downloads page

---

gsoc/index.md
gsoc/projects/index.md

The addition of native SVG rendering is considered a valuable project for wxWidgets and supports the work being carried out on High DPI displays. This PR also updates the important dates section of the index page against the GSOC 2020 calendar.

Add Native SVG Rendering  project for GSOC 2020

---

downloads/downloads.js
downloads/index.md

This allows directly linking to a specic release.
Either using a specic version like:
https://www.wxwidgets.org/downloads#v3.1.3
Or a release channel like this:
https://www.wxwidgets.org/downloads#stable
Or development like this:
https://www.wxwidgets.org/downloads#development
Additionally:
https://www.wxwidgets.org/downloads#v3.1.3_msw
will jump to the same location as #v3.1.3
but the javascript will detect the suffix and will open the popup
with the MSW binaries. (This will only work with a specific version not with stable/development)

Add anchors to the download page

---

downloads/index.md

* Always expand the first available msw binary
* Add explicit compiler ids for VC 2015/2015/2019

Small tweak for compiler list on downloads page

---

_data/releases.yml
_posts/2020-04-25-wxwidgets-3.0.5-released.md

This should be applied after the release is made.
There are other changes required but I am not sure how to do them. In addition to 3.0.5 being the latest stable, there are new compilers: VS 2017 and 2019, MinGW-9.2.0TDM.

wxWidgets 3.0.5 release notice

---

downloads/index.md

Rename "OS X" to "macOS".
Change the link for Release Archive from SourceForge to GitHub.
Remove the link to wxCode, which sadly retired in 2018.

Update text on Downloads page

---

_blog/2020-08-31-implicit_explicit_encoding.md

Following the very long PR on wxWidgets, here is my proposal for a blog post that explain the new macro, why it was introduced and how to use it.
This is my first post on a technical blog and I am trying to make it clear, easy to read and integrated with the other posts.
Please feel absolutely free to criticize _any_ aspect of this post, such as:
- formatting,
- length,
- style, 
- technical errors,
- language errors,
- ...anything else.

Blog post on wxNO_IMPLICIT_WXSTRING_ENCODING macro

---

_posts/2021-05-31-irc-channel-moving-to-libera-chat.md
support/irc/index.md

- Updated the IRC support page, replacing Freenode with Libera Chat.
- Authored a news post announcing the move.

Migrate IRC channel to Libera Chat

---

develop/index.md
thanks/index.md

I have removed Travis CI mention from the Developers page.
In the Thanks page, I have split the _Infrastructure Sponsors_ section into _Current Infrastructure Sponsors_ and _Former Infrastructure Sponsors_ and moved Travis CI into the latter.
I do not really understand the markup nor do I have a possibility to view it as HTML, so the changes in the Thanks page were made blindly and need to be checked.

Update TravisCI information

---

develop/index.md

This mimics the change made for the main readme in the code base: https://github.com/wxWidgets/wxWidgets/commit/e947508da42dc813cdcaa4462c542719c9ea4f12

On the Develop page use master for AppVeyor badge status

---

.github/workflows/publish.yml

This might fix problems with compiling node-sass that prevent the
workflow from working under Ubuntu 18.04 any longer.

Run "publish" workflow under Ubuntu 20.04

---

develop/how-to-report-issues/trac-migration.md

This page is not linked from the rest of the site, but will be used as a
landing page for the redirect from the old wxTrac URL.

Add a page explaining wxTrac to GitHub Issues migration

---

.github/workflows/publish.yml
_cron/update_translation_stats.sh
_cron/update_wxxrc_schema.sh

Using svn doesn't seem to work any longer (the last few runs all have given an error for `svn co` step) and there is no reason to use it anyhow, so switch to Git.

Use git checkout instead of svn to get wx files

---

docs/tutorials/index.md

I took a look at some other tutorials.
**Section IDE Setup/Configuration**
_Programming C++ GUIs with the wxWidgets Library_
Not only it is rather old (published in 2006), I think setup/configuration are not its main focus.
_Intellisense and wxWidgets_ 
The link does not work, moreover, I would expect Intellisense work out of the box these days.
**Section wxWidgets and Others**
_Using wxWidgets with OpenCV_ 
Looks rather obsolete. I think even my [wxOpenCVTest](https://github.com/PBfordev/wxopencvtest) could be more useful nowadays; however, it has just code.

Add another IDE Setup/Configuration tutorial

---

README.md
_config.yml
_posts/2022-04-04-wxwidgets-3.1.6-released.md
index.html

This adds a new "promoted" attribute to posts, which defaults to true. Explicitly adding "promoted: false" to a post will hide it from the home page.

Add ability to hide posts from home page

---

develop/coding-guidelines/index.md

I have made some changes, taking into account Borland C++ is not supported anymore and wxWidgets now requiring compilers supporting modern C++.
Suggestions for further improvements:
I suppose `wxDynamicCast()` is still to be used over `dynamic_cast<>`.

Update coding guidelines

---

support/mailing-lists/index.md

Despite being very low-traffic (20 posts during the past 10 years), and anyone posting there being recommended wx-users instead, wx-discuss was listed without without any hint that it is practically deprecated.

Move wx-discuss to the bottom of lists and state that it is unused

---

downloads/index.md

As the binary filenames only contain the first 3 version components the github assets where not found during download page generation

Fix Windows binaries download for hotfix releases

---

develop/coding-guidelines/index.md

All recommendations in section *Message and documentation conventions* are in imperative form.

Update index.md: Fix imperative form

---

develop/code-repository/index.md

Link to the current version of How to build from Git Sources.
Use more recent branch and tag names in examples.

Update Git Instructions

---

_data/releases.yml
downloads/index.md

These are the changes I had in mind. Simplify the codelite section to use only 1 link.
And define the anaconda URL in releases.yml.
And only show the architecture description when it has assets.

Download improvements
